models/Libros.php
<?php

namespace app\models;

use yii\db\Expression;
use Yii;

/**
 * This is the model class for table "libros".
 *
 * @property int $id
 * @property string|null $ISBN
 * @property string|null $titulo
 * @property string|null $sipnosis
 * @property int|null $num_pag
 * @property string|null $f_publi
 * @property int|null $pagleidas
 * @property float|null $calificacion
 *
 * @property Agregacion[] $agregacions
 * @property Escritores[] $codEscritors
 * @property Escriben[] $escribens
 * @property Generos[] $generos
 */
class Libros extends \yii\db\ActiveRecord {

    public $cod_escritor;

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'libros';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['sipnosis'], 'string'],
            [['num_pag'], 'integer'],
            [['f_publi'], 'safe'],
            [['calificacion'], 'number'],
            [['ISBN'], 'string', 'max' => 20],
            [['titulo'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'ISBN' => 'ISBN',
            'titulo' => 'Título',
            'sipnosis' => 'Sipnosis',
            'num_pag' => 'Páginas',
            'f_publi' => 'Fecha de publicación',
            'calificacion' => 'Calificación',
        ];
    }

    /**
     * Gets query for [[Agregacions]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAgregacions() {
        return $this->hasMany(Agregacion::class, ['cod_libro' => 'id']);
    }

    /**
     * Gets query for [[CodEscritors]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodEscritors() {
        return $this->hasMany(Escritores::class, ['id' => 'cod_escritor'])->viaTable('escriben', ['cod_libro' => 'id']);
    }

    /**
     * Gets query for [[Escribens]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEscribens() {
        return $this->hasMany(Escriben::class, ['cod_libro' => 'id']);
    }

    /**
     * Gets query for [[Generos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGeneros() {
        return $this->hasMany(Generos::class, ['cod_libro' => 'id']);
    }

    //Método que devuelve la calificación de un  usuario y la muestra en el StarRating de la vista
    public function getCalificacionUsuario() {
        $agregacionUsuario = Agregacion::findOne(['cod_libro' => $this->id, 'cod_user' => Yii::$app->user->identity->id]);

        if ($agregacionUsuario) {
            return $agregacionUsuario->calificacion;
        }

        return 0; // Otra valor por defecto si no se encuentra la calificación del usuario
    }

    //Método que devuelve la calificación media de un libroy la muestra en el StarRating de la vista
    public function getCalificacionMedia() {

        return Agregacion::find()
                        ->select(new Expression('AVG(calificacion)'))
                        ->where(['cod_libro' => $this->id])
                        ->andWhere(['>', 'calificacion', 0])
                        ->scalar();
    }

    //Método que devuelve el número de calificación que tiene un libro y la muestra en el StarRating de la vista
    public function getNumCalificaciones() {
        return Agregacion::find()
                        ->where(['cod_libro' => $this->id])
                        ->andWhere(['>', 'calificacion', 0])
                        ->count();
    }

    public function beforeSave($insert) {
        if ($this->f_publi) {
            $this->f_publi = date("Y-m-d", strtotime($this->f_publi));
        }


        return parent::beforeSave($insert);
    }

    public function afterFind() {
        if ($this->f_publi) {
            $this->f_publi = date("d-m-Y", strtotime($this->f_publi));
        }
    }

    //Método para calcular el % léido de un libro
    public function porcentaje_leido($pagleidas) {
        return $pagleidas / $this->num_pag * 100;
    }

}

controllers/LibrosController.php
<?php

namespace app\controllers;

use app\models\Escritores;
use app\models\Generos;
use app\models\Escriben;
use app\models\Estanterias;
use app\models\Agregacion;
use app\models\Libros;
use app\models\Leen;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use yii;
use yii\helpers\Url;

/**
 * LibrosController implements the CRUD actions for Libros model.
 */
class LibrosController extends Controller {

    /**
     * @inheritDoc
     */
    public function behaviors() {
        return array_merge(
                parent::behaviors(),
                [
                    'verbs' => [
                        'class' => VerbFilter::className(),
                        'actions' => [
                            'delete' => ['POST'],
                        ],
                    ],
                ]
        );
    }

    /**
     * Lists all Libros models.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Libros::find(),
                /*
                  'pagination' => [
                  'pageSize' => 50
                  ],
                  'sort' => [
                  'defaultOrder' => [
                  'id' => SORT_DESC,
                  ]
                  ],
                 */
        ]);

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Libros model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Libros model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new Libros();
        $generos = Generos::find()->orderBy('genero')->all();

        $generosSeleccionados = [];
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // Obtener el ID recién creado del libro
            $id = $model->getPrimaryKey();

            // Crear una nueva instancia de la clase "Escribir"
            $escribir = new Escriben();
            $escribir->cod_libro = $id;
            $escribir->cod_escritor = Yii::$app->request->post('Libros')['cod_escritor'];
            $escribir->save();

            // Obtener los géneros seleccionados

            $generos = Yii::$app->request->post('Libros')['generos'];
            foreach ($generos as $genero) {
                $libroGenero = new Generos();
                $libroGenero->cod_libro = $id;
                $libroGenero->genero = $genero;
                $libroGenero->save();
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        // Consultar los géneros y pasarlos a la vista
        $generosArray = ArrayHelper::map($generos, 'genero', 'genero');

        return $this->render('create', [
                    'model' => $model,
                    'generos' => $generosArray,
                    'generosSeleccionados' => $generosSeleccionados,
        ]);
    }

    /**
     * Updates an existing Libros model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        // Obtener el autor actual del libro
        $autores = $model->codEscritors;
        $autorActual = null;
        if (!empty($autores)) {
            // Obtener el primer autor (pueden haber múltiples autores)
            $autorActual = $autores[0]->id;
        }

        // Obtener los géneros disponibles
        $generos = Generos::find()->distinct()->orderBy('genero')->all();

        // Obtener los géneros seleccionados
        $generosSeleccionados = isset($model->generos) ? ArrayHelper::getColumn($model->generos, 'genero') : [];
        $generosActuales = ArrayHelper::getColumn($model->generos, 'genero');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // Actualizar la clave foránea en la tabla "escribir"
            $escribir = Escriben::findOne(['cod_libro' => $id]);

            if (!$escribir) {
                // Si no existe una entrada en la tabla "escribir", crear una nueva instancia
                $escribir = new Escriben();
                $escribir->cod_libro = $id;
            }

            // Asignar el código del autor proporcionado en el formulario de actualización
            $codEscritor = Yii::$app->request->post('Libros')['cod_escritor'];

            // Si el campo oculto "$autorActual" está presente, usar su valor en lugar del valor del campo "cod_escritor"
            $autorActual = Yii::$app->request->post('autorActual');
            if ($codEscritor != $autorActual) {
                $autorActual = $codEscritor;
            }
            if (isset($autorActual)) {
                $codEscritor = $autorActual;
            }


            // Asignar el código del autor al modelo "$model"
            $model->cod_escritor = $codEscritor;
            // Guardar los cambios en el modelo
            $model->save();
            // Actualizar la entrada en la tabla "escribir"
            $escribir->cod_escritor = $codEscritor;
            $escribir->save();

            // Guardar los nuevos géneros
            $generos = Yii::$app->request->post('Libros')['generos'];

            foreach ($generos as $genero) {
                $librosGeneros = new Generos();
                $librosGeneros->cod_libro = $id;
                $librosGeneros->genero = $genero;
                $librosGeneros->save();
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        // Obtener los géneros y pasarlos a la vista
        $generosArray = ArrayHelper::map($generos, 'genero', 'genero');

// Recorrer los géneros y agregar la propiedad "checked" si ya están seleccionados
        foreach ($generosArray as $key => $genero) {
            if (in_array($genero, $generosActuales)) {
                $generosArray[$key] = ['label' => $genero, 'checked' => true];
            } else {
                $generosArray[$key] = ['label' => $genero, 'checked' => false];
            }
        }

        return $this->render('update', [
                    'model' => $model,
                    'generos' => $generosArray,
                    'generosSeleccionados' => $generosSeleccionados,
                    'autorActual' => $autorActual, // Pasar el autor actual a la vista
                    'generosActuales' => $generosActuales, // Pasar los géneros actuales a la vista
        ]);
    }

    /**
     * Deletes an existing Libros model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Libros model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Libros the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Libros::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

//Metodo para actualizar la calificación que le da un usuario al libro desde su vista.
    public function actionActualizarcalificacion($id) {
        $agregacion = Agregacion::findOne(['cod_libro' => $id, 'cod_user' => Yii::$app->user->identity->id]);

        if (!$agregacion) {
            $agregacion = new Agregacion();
            $agregacion->cod_libro = $id;
            $agregacion->cod_user = Yii::$app->user->identity->id;
            $agregacion->cod_estanterias = 3;
            $agregacion->f_agregado = date("Y-m-d");
        }

        $calificacion = Yii::$app->request->post('calificacion');
        $agregacion->calificacion = $calificacion;

        if ($agregacion->save()) {
    //Una vez actualizada la calificación, nos redirige de nuevo a la página, recargándola y mostrando la calificación añadida
            return $this->redirect(['view', 'id' => $id]);
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['success' => false, 'errors' => $agregacion->getErrors()];
        }
    }

}

views/libros/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\editors\Summernote;
use kartik\date\DatePicker;
use kartik\widgets\StarRating;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use app\models\Escritores;
use app\models\Generos;
/** @var yii\web\View $this */
/** @var app\models\Libros $model */
/** @var yii\widgets\ActiveForm $form */


?>

<div class="libros-form">

    <?php $form = ActiveForm::begin();
?>
<div class="form-group">
    <?= $form->field($model, 'ISBN')->textInput(['maxlength' => true,'placeholder' => 'Escribe el ISBN del libro']) ?>
</div>
<div class="form-group">
    <?= $form->field($model, 'titulo')->textInput(['maxlength' => true,'placeholder' => 'Escribe el título del libro']) ?>
</div>
<div class="form-group">
<?= $form->field($model, 'cod_escritor')->label('Escritor')->dropDownList(Escritores::getEscritoresOptions(), ['value' => isset($autorActual) ? $autorActual : null]) ?>
<?= isset($autorActual) ? Html::hiddenInput('autorActual', $autorActual) : '' ?>
 </div>
    <div class="form-group">
<?php $generosSeleccionados = isset($generosSeleccionados) ? $generosSeleccionados : []; ?>

<?php foreach ($generos as $key => $genero) : ?>
    <div class="form-check">
        <?= Html::checkbox("Libros[generos][]", isset($genero['checked']) && $genero['checked'], ['label' => isset($genero['label']) ? $genero['label'] : $genero, 'value' => $key]) ?>
    </div>
<?php endforeach; ?>

    </div>
<div class="form-group">
    <?= $form->field($model, 'num_pag')->textInput(['placeholder' => 'Escribe el número de páginas del libro']) ?>
</div>
<div class="form-group">
    <?= $form->field($model, 'f_publi') ->widget(DatePicker::classname(), [
  'name'=>'f_publi',
    'value'=>'2015-10-19',
        'options' => ['placeholder' => 'Seleccione una fecha'],
   //'useWithAddon'=>true,
    'convertFormat'=>true,
    'pluginOptions'=>[
         'todayHighlight' => true,
         'todayBtn' => true,
       'autoclose' => true,
        'format' => 'dd-M-yyyy',
    ]
]) 
            ?>
</div>

<div class="form-group">   
    <?= $form->field($model, 'sipnosis')->widget(Summernote::class, [
 'useKrajeePresets' => true,
        'pluginOptions'=>[
    'height' => 200,
    'dialogsFade' => true,
    'toolbar' => [
        ['style1', ['style']],
        ['style2', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript']],
        ['font', ['fontname', 'fontsize', 'color', 'clear']],
        ['para', ['ul', 'ol', 'paragraph', 'height']],
        ['insert', ['link', 'picture', 'video', 'table', 'hr']],
    ],
    'fontSizes' => ['8', '9', '10', '11', '12', '13', '14', '16', '18', '20', '24', '36', '48'],
    'codemirror' => [
      //  'theme' => Codemirror::DEFAULT_THEME,
        'lineNumbers' => true,
        'styleActiveLine' => true,
        'matchBrackets' => true,
        'smartIndent' => true,
        'enablePrettyFormat'=>false,
        'autoFormatCode'=>false,
        
    ],
             'placeholder' => 'Escribe la sipnosis del libro',
]

]);?>
   
</div>

     <div class="form-group">
         <?= Html::resetButton('Borrar', ['class' => 'btn btn-secondary btn-default']) ?>
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/libros/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Libros $model */

$this->title = 'Nuevo Libro';
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="libros-create administradores">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
    'generosSeleccionados' => $generosSeleccionados,
        'generos' => $generos,
          // 'escritoresOptions'=>$escritoresOptions,

    ]) ?>

</div>

views/libros/index.php
<?php

use app\models\Libros;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Libros';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="libros-index admintabla">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nuevo Libro', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'titulo',
            'ISBN',
           [
            'attribute' => 'sipnosis',
            'format' => 'raw',
            ],
            'num_pag',
            //'f_publi',
            //'pagleidas',
            //'calificacion',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Libros $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/libros/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Libros $model */

$this->title = 'Modificar ' . $model->titulo;
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->titulo, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Modificar';
?>
<div class="libros-update administradores">

    <h2><?= Html::encode($this->title) ?></h2>

     <?= $this->render('_form', [
        'model' => $model,
         'autorActual' => $autorActual,
          'generos' => $generos,
         'generosSeleccionados' => $generosSeleccionados,
        'generosActuales' => $generosActuales, // Pasar los géneros actuales a la vista
        // 'escritoresOptions'=>$escritoresOptions,
      //   'autores'=>$autores,
    ]) ?>

</div>

views/libros/view.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\ArrayHelper;
use kartik\widgets\StarRating;
use yii\helpers\Url;

/** @var yii\web\View $this */
/** @var app\models\Libros $model */
$this->title = $model->titulo;
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['site/libros']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="libros-view superior-view">
    <?php
    if (Yii::$app->user->isGuest) {
        Yii::$app->getResponse()->redirect(Yii::$app->getUser()->loginUrl);
    } else {
        ?>

        <div class="libros-lateral"> 
            <div class="info-portada-libro" >  
                <?= Html::img('@web/img/' . $model->id . '.jpg', ['alt' => 'Portada', 'class' => 'libro detail ']) ?>
                <!-- Opción de calificar un libro -->
                <p>
                    <?=
                    StarRating::widget([
                        'name' => 'input-4',
                        'value' => $model->getCalificacionUsuario(), // Asigna el valor de la calificación del modelo aquí
                        'pluginOptions' => [
                            'showClear' => false,
                            'showCaption' => false,
                            'step' => 0.5,
                            'size' => 'md',
                        ],
                        'pluginEvents' => [
                            'rating:change' => 'function(event, value, caption) {
                                            $.ajax({
                                                url: "' . Url::to(['libros/actualizarcalificacion', 'id' => $model->id]) . '",
                                                method: "POST",
                                                data: {
                                                calificacion: value, 
                                                 },
                                                success: function(response) {
                                                    console.log("Calificación actualizada exitosamente");
                                                },
                                                error: function(xhr, status, error) {
                                                    console.error("Error al actualizar la calificación:", error);
                                                }
                                            });
                                        }'
                        ]
                    ]);
                    ?>
                </p>
                <!-- Botón para añadir a una estantería -->
                <?= Html::a('Añade a una estantería', ['agregacion/add-to-shelf', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>

            </div> 
        </div>
        <div class="info-libro">
            <h2><?= $model->titulo ?></h2>
            <div class="ranking">

                <?=
                StarRating::widget([
                    'name' => 'rating_33',
                    'value' => $model->calificacionMedia,
                    'pluginOptions' => [
                        'size' => 'sm',
                        'readonly' => true,
                        'showClear' => false,
                        'showCaption' => true,
                        'language' => 'es',
                    ],
                ]);
                ?> 
                <?php if ($model->calificacionMedia > 0) : ?>
                    <span class="numcalificacion"><?= $model->numCalificaciones ?> <?= $model->numCalificaciones == 1 ? 'calificación' : 'calificaciones' ?>
                    </span>   <?php endif; ?>
            </div>
            <!-- Escritores de un libro -->
            <div class="autores">
                <?php
                $escritores = $model->codEscritors;
                foreach ($escritores as $escritor) {
                    $enlace = Yii::$app->urlManager->createUrl(['escritores/view', 'id' => $escritor->id]);
                    echo '<a href="' . $enlace . '">' . $escritor->nombre . '</a><br>';
                }
                ?>
            </div>
            <!-- Géneros de un libro -->
            <div class="genero" >
                <?php
                $generos = $model->generos;
                foreach ($generos as $genero) {
                    $enlace = Yii::$app->urlManager->createUrl(['site/genero', 'genero' => $genero->genero]);
                    echo '<a href="' . $enlace . '">' . $genero->genero . '</a>   <br>';
                }
                ?>
            </div>  


            <div class="sipnosis">  
                <?= $model->sipnosis ?>
            </div>  




            <!-- Comentarios de los libros -->
            <div class="comentarios-libros">
                <h3>Calificaciones y reseñas</h3>

                <?= Html::a('Añade un comentario', ['comentarios/comentario', 'codlibro' => $model->id], ['class' => 'btn btn-primary']) ?>
                <p> </p>


                <?php $hasComments = false; ?>
                <?php foreach ($model->agregacions as $agregacion) : ?>
                    <?php if (empty($agregacion->comentarios)) : ?>
                        <?php continue; ?>
                    <?php else : ?>
                        <?php $hasComments = true; ?>
                        <?php foreach ($agregacion->comentarios as $comentario) : ?>
                            <div class="comentarios">
                                <div class="perfil">
                                    <?= Html::img('@web/img/user/' . $agregacion->codUser->id . '.jpg') ?>
                                    <p><?= $agregacion->codUser->username ?></p>

                                </div>
                                <div class="comentario">
                                    <span><?= $agregacion->f_agregado ?></span>
                                    <?= $comentario->comentario ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <!--En caso de que no haya ningún comentario -->
                <?php if (!$hasComments) : ?>
                    <p>Aún no hay comentarios.</p>
                <?php endif; ?>


            </div>
        </div>
    <?php } ?>
</div>