controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\FormRegister;
use app\models\Users;
use app\models\User;
use app\models\Libros;
use app\models\Generos;
use app\models\Agregacion;
use app\models\Retos;
use app\models\Participaciones;
use app\models\Estanterias;
use app\models\Tags;
use app\models\Escritores;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\data\ActiveDataProvider;
use yii\web\JsonResponse;
use yii\web\JsExpression;
use yii\data\ArrayDataProvider;
use yii\db\Expression;
use yii\web\Session;
use app\models\FormRecoverPass;
use app\models\FormResetPass;

class SiteController extends Controller {

    public function actionEstanteria() {


        // Obtener las estanterías para mostrarlas en la vista
        $estanterias = Estanterias::find()->all();
        $this->view->title = 'Todos mis libros';
        $libros = Libros::find()
                ->joinWith([
                    'agregacions' => function ($query) {
                        $query->where(['agregacion.cod_user' => Yii::$app->user->identity->id]);
                    }
                ])
                ->all();

        //Mostrar el total de libros
        $cantidadLibro = Agregacion::find()
                ->select(['cod_estanterias', 'count(*) as total'])
                ->where(['cod_user' => Yii::$app->user->identity->id])
                ->groupBy(['cod_estanterias'])
                ->asArray()
                ->all();

        $cantidadLibros = [];
        foreach ($cantidadLibro as $item) {
            $cantidadLibros[$item['cod_estanterias']] = $item['total'];
        }

        $countLibros = Agregacion::find()
                ->select(['cod_user', 'count(*) as total'])
                ->where(['cod_user' => Yii::$app->user->identity->id])
                ->groupBy(['cod_user'])
                ->asArray()
                ->one();

        $dataProvider = new ArrayDataProvider([
            'allModels' => $libros,
        ]);

        //sección para los libros que estan en la estantería de leyenho
        $estanteriaLeyendoActualmente = Estanterias::findOne(['nombre' => 'Leyendo']);
        $estanteriaLeyendoActualmenteId = $estanteriaLeyendoActualmente->id;

        $librosLeyendoActualmente = Libros::find()
                ->joinWith([
                    'agregacions' => function ($query) use ($estanteriaLeyendoActualmenteId) {
                        $query->where([
                            'agregacion.cod_user' => Yii::$app->user->identity->id,
                            'agregacion.cod_estanterias' => $estanteriaLeyendoActualmenteId
                        ]);
                    }
                ])
                ->all();

        //Información sobre los retos.
        $model = Participaciones::find()->where(['cod_user' => Yii::$app->user->identity->id])->one();
        $librosusuario = Agregacion::find()->where(['cod_estanterias' => 2, 'cod_user' => Yii::$app->user->identity->id])
                        ->andWhere(['between', 'f_agregado', '2023-01-01', '2023-12-31'])->count();

        //Información sobre los tags.
        $tags = Tags::find()
                ->joinWith('codAgregar') // Unir con la relación "codAgregar" en el modelo Tags
                ->where([
                    'cod_user' => Yii::$app->user->identity->id,
                ])
                ->groupBy('tag')
                ->all();

        if ($librosusuario > 0) {
            $porcentaje = ($librosusuario / $model->objetivo) * 100;
        } else {
            $porcentaje = 0; // Para evitar división por cero si no hay participantes
        }
        // Renderizar la vista y pasar los datos a la vista
        return $this->render('estanteria', [
                    'dataProvider' => $dataProvider,
                    'estanterias' => $estanterias,
                    'cantidadLibros' => $cantidadLibros,
                    'countLibros' => $countLibros,
                    'librosLeyendoActualmente' => $librosLeyendoActualmente,
                    'model' => $model,
                    'librosusuario' => $librosusuario,
                    'porcentaje' => $porcentaje,
                    'tags' => $tags,
        ]);
    }

    public function actionEstanteriaid($id) {
        // Obtener las estanterías para mostrarlas en la vista
        $estanteria = Estanterias::find()->where(['id' => $id])->one();
        $estanterias = Estanterias::find()->all();

        if ($estanteria !== null) {
            $this->view->title = $estanteria->nombre;

            $libros = Libros::find()
                    ->joinWith([
                        'agregacions' => function ($query) use ($estanteria) {
                            $query->where([
                                'agregacion.cod_user' => Yii::$app->user->identity->id,
                                'agregacion.cod_estanterias' => $estanteria->id,
                            ]);
                        }
                    ])
                    ->all();

            //Cantidad de libros
            $countLibros = Agregacion::find()
                    ->select(['cod_user', 'count(*) as total'])
                    ->where(['cod_user' => Yii::$app->user->identity->id])
                    ->groupBy(['cod_user'])
                    ->asArray()
                    ->one();

            $cantidadLibro = Agregacion::find()
                    ->select(['cod_estanterias', 'count(*) as total'])
                    ->where(['cod_user' => Yii::$app->user->identity->id])
                    ->groupBy(['cod_estanterias'])
                    ->asArray()
                    ->all();

            $cantidadLibros = [];
            foreach ($cantidadLibro as $item) {
                $cantidadLibros[$item['cod_estanterias']] = $item['total'];
            }

            $dataProvider = new ArrayDataProvider([
                'allModels' => $libros,
            ]);

            //Libros leyendo actualmente
            $estanteriaLeyendoActualmente = Estanterias::findOne(['nombre' => 'Leyendo']);
            $estanteriaLeyendoActualmenteId = $estanteriaLeyendoActualmente->id;

            $librosLeyendoActualmente = Libros::find()
                    ->joinWith([
                        'agregacions' => function ($query) use ($estanteriaLeyendoActualmenteId) {
                            $query->where([
                                'agregacion.cod_user' => Yii::$app->user->identity->id,
                                'agregacion.cod_estanterias' => $estanteriaLeyendoActualmenteId,
                            ]);
                        }
                    ])
                    ->all();

            //Información sobre los retos
            $model = Participaciones::find()->where(['cod_user' => Yii::$app->user->identity->id])->one();
            $librosusuario = Agregacion::find()
                    ->where([
                        'cod_estanterias' => 2,
                        'cod_user' => Yii::$app->user->identity->id,
                    ])
                    ->andWhere(['between', 'f_agregado', '2023-01-01', '2023-12-31'])
                    ->count();

            if ($librosusuario > 0) {
                $porcentaje = ($librosusuario / $model->objetivo) * 100;
            } else {
                $porcentaje = 0;
            }

            //Información sobre los tags
            $tags = Tags::find()
                    ->joinWith('codAgregar')
                    ->where([
                        'cod_user' => Yii::$app->user->identity->id,
                    ])
                    ->groupBy('tag')
                    ->all();

            return $this->render('estanteria', [
                        'dataProvider' => $dataProvider,
                        'estanteria' => $estanteria,
                        'estanterias' => $estanterias,
                        'cantidadLibros' => $cantidadLibros,
                        'countLibros' => $countLibros,
                        'librosLeyendoActualmente' => $librosLeyendoActualmente,
                        'model' => $model,
                        'librosusuario' => $librosusuario,
                        'porcentaje' => $porcentaje,
                        'tags' => $tags,
            ]);
        }
    }

//Método para conseguir los libros filtranfo por los tags
    public function actionTag($tag) {


        $tag = Tags::find()->where(['tag' => $tag])->one();

        if ($tag !== null) {
            $this->view->title = 'Tus libros de ' . $tag->tag;

            $tags = Tags::find()
                    ->joinWith('codAgregar')
                    ->where([
                        'cod_user' => Yii::$app->user->identity->id,
                    ])
                    ->groupBy('tag')
                    ->all();
        }

        $libros = Libros::find()
                ->joinWith('agregacions.tags')
                ->where(['tags.tag' => $tag])
                ->all();

        $dataProvider = new ArrayDataProvider([
            'allModels' => $libros,
        ]);

        return $this->render('tag', [
                    'tags' => $tags,
                    'dataProvider' => $dataProvider
        ]);
    }

//Método para conseguir la información del reto de cada usuario
    public function actionTusretos() {
        $model = Participaciones::find()->where(['cod_user' => Yii::$app->user->identity->id])->one();

        $reto = Retos::find()->where(['nombre' => '2023'])->one();

        $dataProvider = new ActiveDataProvider([
            'query' => Agregacion::find()
                    ->where([
                        'cod_user' => Yii::$app->user->identity->id,
                        'cod_estanterias' => 2,
                    ])
                    ->andWhere(['between', 'f_agregado', '2023-01-01', '2023-12-31'])
        ]);

views/site/_autor.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
?>


<div class="col-sm-12">
    <div class="card autores">

        <?= Html::img('@web/img/autor/' . $model->nombre . '.jpg', ['alt' => 'Autor', 'class' => 'escritoresImg']) ?>

        <?= Html::a($model->nombre, ['escritores/view', 'id' => $model->id], ['class' => 'h6']) ?>

    </div>
</div>

views/site/_estante.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
?>


<div class="col-sm-12">

    <?= Html::a(Html::img('@web/img/' . $model->id . '.jpg', ['alt' => 'Portada', 'class' => 'book estante']), ['libros/view', 'id' => $model->id]) ?>

</div>

views/site/_libroreto.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
?>


<div class="col-sm-12">
    <div class="card minimo">

        <?= Html::a(Html::img('@web/img/' . $model->cod_libro . '.jpg', ['alt' => 'Portada', 'class' => 'book cover']), ['libros/view', 'id' => $model->cod_libro]) ?>

    </div>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contáctanos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact superior">
    <div class="formularioDiferente"><h2><?= Html::encode($this->title) ?></h2>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
           Gracias por ponerte en contacto con nosotros. Te responderemos con la mayor brevedad posible.
        </div>

       

    <?php else: ?>

        <p>
           Si tienes alguna duda o sugerencia, por favor, ponte en contacto con nosotros. Gracias. 
           
        </p>

        <div class="row">
            <div class="col-lg-11">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name', [
   'labelOptions' => ['label' => 'Nombre']])->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject', [
   'labelOptions' => ['label' => 'Asunto']]) ?>

                    <?= $form->field($model, 'body', [
   'labelOptions' => ['label' => 'Su mensaje']])->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-5">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
        </div>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error superior">

    <h2><?= Html::encode($this->title) ?></h2>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/escritores.php
<?php

use app\models\Escritores;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\widgets\ListView;

/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */
$this->title = 'Nuestros escritores';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="escritores-index superior">

    <h2><?= Html::encode($this->title) ?></h2>

    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_autor',
        'layout' => "\n{items}\n\n{pager}",
    ]);
    ?>

</div>

views/site/estanteria.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;
use yii\widgets\ListView;
use yii\grid\ActionColumn;
use yii\grid\GridView;

$this->params['breadcrumbs'][] = ['label' => 'Estanterias ', 'url' => ['site/estanteria']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="estanterias-index superior">
    <h2>
<?= Html::encode($this->title) ?>
    </h2>
        <?php
        if (Yii::$app->user->isGuest) {

            Yii::$app->getResponse()->redirect(Yii::$app->getUser()->loginUrl);
        } else {
            ?>

        <div class="estanteria-index">

            <div class="pag-estanteria">
 <!-- Vista de los libros de la estantería -->

    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_estante',
        'layout' => "{items}{pager}",
    ]);
    ?>

            </div>
            <div class="sidebar-busqueda">
                <h5>Mis estanterías</h5>
                <br>
                 <!-- Lista con las estanterías y el número de libros en cada una -->
    <?php if ($countLibros['total'] == 0) : ?>
                    <span>Añade algún libro a tu estantería.</span>
                <?php else : ?>
                    <?= Html::a('Todos mis libros', ['site/estanteria']) ?> (
                    <?= $countLibros['total'] ?>)


        <?php foreach ($estanterias as $estanteria): ?>
                        <br>
                        <?= Html::a($estanteria->nombre, ['site/estanteriaid', 'id' => $estanteria->id]) ?>

                        <?php if (isset($cantidadLibros[$estanteria->id])): ?>
                            <span>(
                            <?= $cantidadLibros[$estanteria->id] ?> )
                            </span>
                            <?php else: ?>
                            <span>(0)</span>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                            
                             <!-- Lista de las etiquetas personales de los usuarios de tenerlas -->
                <?php foreach ($tags as $tag): ?>
                    </br><?= Html::a($tag->tag, ['site/tag', 'tag' => $tag->tag]) ?>
                <?php endforeach; ?>

                     <!-- Zona de lecturas actuales -->
                <div class="actual">
                    <h5>Lecturas actuales</h5>
                    <br>
    <?php if (empty($librosLeyendoActualmente)) : ?>
                        <span>   No estás leyendo nada en este momento. </span>
                    <?php else : ?>
                        <?php foreach ($librosLeyendoActualmente as $libro): ?>
                            <div class="libro" data-libro-id="<?= $libro->id ?>">
                            <?= Html::img('@web/img/' . $libro->id . '.jpg', ['alt' => 'Portada', 'class' => 'leyendo book']) ?>
                                <div class="libroactualinfo">
                                <?= Html::a($libro->titulo, ['libros/view', 'id' => $libro->id], ['class' => 'd-inline-block text-truncate']) ?>
                                    <p>de
                                    <?= Html::a($libro->getCodEscritors()->one()->nombre, ['escritores/view', 'id' => $libro->getCodEscritors()->one()->id]) ?>
                                    </p>


            <?php $porcentajeLeido = $libro->porcentaje_leido($libro->agregacions[0]->paginasleidas); ?>



                                    <div class="progress" id="progresoLibro<?= $libro->id ?>">

                                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                                             style="width: <?= $porcentajeLeido ?>%"
                                             aria-valuenow="<?= $libro->agregacions[0]->paginasleidas ?>" aria-valuemin="0"
                                             aria-valuemax="<?= $libro->num_pag ?>">

                                        </div>

                                    </div>
                                    <div id="texto-progreso<?= $libro->id ?>">
            <?= $libro->agregacions[0]->paginasleidas ?> / <?= $libro->num_pag ?>
                                        (<?= round($libro->porcentaje_leido($libro->agregacions[0]->paginasleidas)) ?>%)
                                    </div>



                                    <!-- Botón que abre el modal -->
            <?=
            Html::button('Actualizar', [
                'class' => 'btn btn-outline-secondary btn-sm actualizar',
                'data-toggle' => 'modal',
                'data-target' => '#actualizarModal' . $libro->id,
            ])
            ?>


                                    <!-- Modal correspondiente a cada libro -->
                                    <div class="modal fade" id="actualizarModal<?= $libro->id ?>" tabindex="-1" role="dialog"
                                         aria-labelledby="actualizarModalLabel<?= $libro->id ?>" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="actualizarModalLabel<?= $libro->id ?>">Actualizar
                                                        páginas leídas de <?= $libro->titulo ?></h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="form-group">
                                                        <?= Html::label('Páginas leídas') ?>
                                                        <?= Html::input('number', 'paginasLeidas', $libro->agregacions[0]->paginasleidas, ['class' => 'form-control', 'id' => 'paginasLeidas' . $libro->id]) ?>
                                                    </div>
                                                    <p>
                                                        <?= Html::a('¡Lo he terminado!', ['agregacion/actualizacion', 'id' => $libro->id]) ?>
                                                    </p>
                                                    <button class="btn-actualizar" class="btn btn-outline-secondary btn-sm"
                                                            data-toggle="modal" data-target="#actualizarModal<?= $libro->id ?>"
                                                            data-id="<?= $libro->id ?>"
                                                            data-paginas="<?= $libro->num_pag ?>">Actualizar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <div class="estanteria-reto">
                    <h5>Reto de Lectura</h5>
                    <div class="info-reto-estanteria">
                        <div class="badgeYearestanteria">
                            <span class="yearHeaderestanteria">2023</span>
                            <?= Html::img('@web/img/icon/icon2.png', ['alt' => 'IconoRetoestanteria ', 'class' => 'bookImgretoestanteria']) ?>
                            
                        </div>
                        <div class="retosestadisticas"> 
                            <?php if (empty($model->objetivo)) : ?>
                                <p>Participa en el <a href="<?= \yii\helpers\Url::to(['participaciones/reto'], true) ?>">reto</a>.</p>
                            <?php else : ?>
                                <?php if ($librosusuario >= $model->objetivo) : ?>
                                    <span>¡Reto completado!</span>
                                <?php endif; ?>
                                <p>Has leído <span><?= $librosusuario ?></span> de tu objetivo de <span><?= $model->objetivo ?></span> libros</p>

                                <div class="progress"><div class="progress-bar"  style="width: <?= $porcentaje ?>%"></div> </div>
                                <span><?= round($porcentaje)?>%</span>



                            <?php endif; ?>
                        </div> 
                    </div>
                </div>

            </div>
        </div>

    <?php } ?>
</div>

views/site/generos.php
<?php
use yii\helpers\Html;
use  yii\widgets\ListView;
use  yii\widgets\LinkPager;
/** @var yii\web\View $this */


$this->params['breadcrumbs'][] = $this->title;
?>
<div class="generos-index superior">
  <h2><?= Html::encode($this->title) ?></h2>
  <div class="g-index">
       <section class="pag-busqueda">
    <?=   ListView::widget([
            'dataProvider' => $dataProvider,
          
             'itemView' => '_libro',
              'layout'=>"\n{items}",

          ]);
  ?>
</section>
 
  <section class="sidebar-busqueda">
      <h4>Géneros</h4>
       
                    <?php foreach ($generos as $genero): ?>
                       <br>
              <?= Html::a($genero->genero, ['site/genero', 'genero' => $genero->genero]) ?>

                                       
                    <?php endforeach; ?>
  </section>
  </div>
</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\LinkPager;
use kartik\widgets\StarRating;

/** @var yii\web\View $this */
$this->title = 'BookMate';
?>
<!-- Header -->
<div id="portada">
    <h1>
        <?= Html::encode($this->title) ?>
    </h1>
</div>
<!-- Fin header -->
<div class="site-index superior"> 
    <!-- Inicio mejores libros -->
    <div class="bg">
        <h2>Los mejor valorados</h2>  

        <div class="hero-section">

            <div class="card-grid">
                <?php foreach ($mejoresLibros->getModels() as $index => $libro): ?>
                    <a class="card2" href="<?= Yii::$app->urlManager->createUrl(['libros/view', 'id' => $libro->id]) ?>">
                        <div class="card_background"
                             style="background: url('<?= Yii::getAlias('@web') ?>/img/<?= $libro->id ?>.jpg'); background-size: cover;    background-position:center;">
                        </div>

                        <div class="card_content">

                            <h3 class="card_heading">
                                <?=
                                StarRating::widget([
                                    'name' => 'rating_33',
                                    'value' => $libro->calificacionMedia,
                                    'pluginOptions' => [
                                        'size' => 'sm',
                                        'readonly' => true,
                                        'showClear' => false,
                                        'showCaption' => false,
                                        'language' => 'es',
                                    ],
                                ]);
                                ?>
                            </h3>
                        </div>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>

    </div>
    <!-- Fin Mejores libros -->
    <div class="separador"></div>


    <!-- Inicio Info reto -->
    <div class="reto-actual">
        <?= Html::img('@web/img/icon/icon2.png', ['alt' => 'IconoReto', 'class' => 'bookImg']) ?>
        <div class="year">
            Reto de Lectura 2023
        
        <span>¿Quieres marcarte un objetivo de lectura este año?</span>
            <?php
            if (!Yii::$app->user->isGuest) {
                if (!empty($participacion) && isset($participacion->objetivo)) {
                    // $participacion es un objeto y tiene la propiedad 'objetivo'
                    echo Html::a('Actualizar tu objetivo', ['participaciones/reto'], ['class' => 'btn btn-success']);
                } else {
                    // $participacion no es un objeto o no tiene la propiedad 'objetivo'
                    echo Html::a('Participar', ['participaciones/reto'], ['class' => 'btn btn-success']);
                }
            }
            ?>



        </div>
        <!-- Información sobre los retos -->
        <div class="challengeStats">

            <div class="challengeStatItem">Participantes</div>
            <div class="statNumber">
                <?= $participantes ?>
            </div>
            <div class="challengeStatItem">Libros leídos</div>
            <div class="statNumber">
                <?= $libros ?>
            </div>
            <div class="challengeStatItem">Media de Libros</div>
            <div class="statNumber">
                <?= $mediaLibrosPorParticipante ?>
            </div>
            <div class="challengeStatItem">Páginas leídas</div>
            <div class="statNumber">
                <?= $paginas ?>
            </div>
        </div>
    </div>
    <!-- Fin retp -->
    <!-- Inicio novedades -->
    <div class="bg">
        <h2>Nuestras novedades</h2>

        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_libro',
            'layout' => "\n{items}",
        ]);
        ?>
        <?php
        if (!Yii::$app->user->isGuest) {
            echo Html::a('Ver más', ['libros'], ['class' => 'btn btn-success centrado']);
        }
        ?>

    </div>
    <!-- Fin novedades -->
</div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Conectarse';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login superior">
    <div class="formularioDiferente">
        <h2><?= Html::encode($this->title) ?></h2>

    <p>Rellena los campos para conectarte:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-3 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-7 form-control'],
            'errorOptions' => ['class' => 'col-lg-9 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->label('Usuario')->textInput(['autofocus' => true,'placeholder' => 'Introduce tu nombre de usuario']) ?>

        <?= $form->field($model, 'password')->label('Contraseña')->passwordInput(['placeholder' => 'Introduce tu contraseña']) ?>

            
        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-5 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-4 col-lg-12">
                <?= Html::submitButton('Conectarse', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>  
            </div>
    
          
        </div>
       <div class="form-group">
           <p> <?= Html::a('¿Has olvidado la Contraseña?',['recoverpass' ]) ?> </p>
           <p>¿Aún no tienes cuenta? <?= Html::a('Crea tu cuenta',['register' ]) ?> </p>
            </div>
    

    <?php ActiveForm::end(); ?>

    </div>
</div>